### ISSUE TITLE
example for returning more than 1 value for native

### ISSUE THREAD

**Issue by foxthefox** [mcm1957/ioBroker.jsonconfig-demo#5]
can you please add an example for returning more than one value via native?

I have 4 values in the config page to be set by returning them from a function in sendTo.

in jsonUIconfig I have:
```
		"mqttUserId": {
			"type": "text",
			"label": "mqtt userId",
			"newLine": false
		},
		"mqttUserName": {
			"type": "text",
			"label": "mqtt user name",
			"newLine": false
		},
		"mqttPwd": {
			"type": "text",
			"label": "mqtt pwd",
			"newLine": true
		},
		"mqttClientId": {
			"type": "text",
			"label": "mqttClientId",
			"newLine": false
		},
		"_create": {
			"type": "sendTo",
			"label": "Create Login Data",
			"command": "create",
			"variant": "outlined",
			"useNative": true,
			"jsonData": "{\"user\": \"${data.mqttUserName}\", \"pass\": \"${data.mqttPwd}\"}}"
		}
```

and in the message portion I have 
```
	const resultFromFunction = {
		native: {
			mqttUserId: '1232445564356',
			mqttUserName: 'login.User',
			mqttPwd: 'login.Password',
			mqttClientId: 'login.clientID'
		}
	};
	this.sendTo(obj.from, obj.command, resultFromFunction, obj.callback);
```

after returning the message only the last value is modified in the config page of the adapter.
If I reduce it to one value, it is running OK.

**Comment by mcm1957** [comment]
I can add it if someone canbzell how it works. I do not even know if its possible. 

Note: I did not develop jsonconfig or its components.

**Comment by ticaki** [comment]
I couldn't get this to work either. Its a Admin missing feature/bug imho.

**Comment by foxthefox** [comment]
OK, I transfer this to the admin adapter
